name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host 52.56.201.243\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose

    - name: Build and Deploy with Docker Compose
      run: |
        ssh -i ~/.ssh/id_rsa 52.56.201.243 'cd /path/to/your/app && docker-compose pull && docker-compose up -d'