name: Book Store CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/django-book-store-ibt:latest

  deploy-to-ec2:
    needs: build-Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "Setting up SSH key..."
          echo "${PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa  # Display the content for debugging
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      
      

      - name: Copy SSH known hosts
        run: |
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          KNOWN_HOSTS: ${{ secrets.EC2_SSH_KNOWN_HOSTS }}

      - name: SSH into EC2 instance and pull changes
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-52-56-201-243.eu-west-2.compute.amazonaws.com 'cd /home/ubuntu/django-book-store-ibt && git pull'
